name: CI and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      
      # Clean npm cache and install dependencies
      - name: Clean and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install -g npm@latest
          npm install
      
      # Build tokens and react packages
      - name: Build packages
        run: |
          # Build tokens package
          cd packages/tokens
          npm install
          npm run build
          cd ../..
          
          # Build react package
          cd packages/react
          npm install
          npm run clean || true
          npx vite build || true
          npm run build:css || true
          cd ../..
      
      # Only publish from main branch
      - name: Publish packages to npm
        if: github.ref == 'refs/heads/main'
        run: |
          # Create changeset directory if it doesn't exist
          mkdir -p .changeset
          
          # Create a changeset file
          cat > .changeset/publish-to-npm.md << EOF
---
"@tagaddod-design/tokens": patch
"@tagaddod-design/react": minor
---

Update tokens package and publish initial release of React components
EOF
          
          # Install changeset CLI
          npm install -g @changesets/cli
          
          # Update versions
          npx changeset version
          
          # Ensure npm authentication is set up correctly
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          
          # Debug token and auth setup
          echo "--- Checking npm configuration ---"
          npm config list
          
          # Try to publish packages (react first since it depends on tokens)
          echo "--- Publishing React package ---"
          cd packages/react
          npm publish --access public || echo "React package publish failed or already exists"
          
          echo "--- Publishing tokens package ---"
          cd ../tokens
          npm publish --access public || echo "Tokens package publish failed or already exists"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TAGADDOD_DESIGN }}
