name: CI and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      
      # Clean npm cache and install dependencies
      - name: Clean and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install -g npm@latest
          npm install
      
      # Build and publish tokens package only for now
      - name: Build tokens package
        run: |
          cd packages/tokens
          npm install
          npm run build
      
      # Only publish from main branch
      - name: Publish tokens package to npm
        if: github.ref == 'refs/heads/main'
        run: |
          # Create changeset directory if it doesn't exist
          mkdir -p .changeset
          
          # Create a changeset file
          cat > .changeset/publish-to-npm.md << EOF
---
"@tagaddod-design/tokens": minor
---

Initial release of Tagaddod Design System tokens package
EOF
          
          # Install changeset CLI
          npm install -g @changesets/cli
          
          # Update version
          npx changeset version
          
          # Debug .npmrc
          echo "--- Checking .npmrc for auth ---"
          cat ~/.npmrc || echo "No ~/.npmrc file found"
          echo "--- Setting up .npmrc manually ---"
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          
          # Debug token availability (masked)
          echo "--- Checking if token is available ---"
          if [ -n "$NODE_AUTH_TOKEN" ]; then
            echo "TOKEN AVAILABLE ✅ (masked for security)"
          else
            echo "TOKEN NOT AVAILABLE ❌"
          fi
          
          # Debug npm whoami
          echo "--- Checking npm identity ---"
          npm whoami || echo "Not logged in to npm"
          
          # Attempt to publish
          echo "--- Publishing package ---"
          cd packages/tokens
          npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TAGADDOD_DESIGN }}
