name: CI and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install
      
      # Build tokens package
      - name: Build tokens package
        run: |
          cd packages/tokens
          npm install
          npm run build
      
      # Build react package
      - name: Build react package (skip TypeScript)
        run: |
          cd packages/react
          npm install
          npm run clean || true
          npx vite build
          npm run build:css || true
      
      # Only publish from main branch
      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        run: |
          # Create changeset directory if it doesn't exist
          mkdir -p .changeset
          
          # Create a changeset file if none exists
          if [ ! -f ".changeset/publish-to-npm.md" ]; then
            cat > .changeset/publish-to-npm.md << 'EOF'
---
"@tagaddod-design/tokens": minor
"@tagaddod-design/react": minor
---

Initial release of Tagaddod Design System
EOF
          fi
          
          # Install changeset CLI
          npm install -g @changesets/cli
          
          # Update versions
          npx changeset version
          
          # Publish to npm
          cd packages/tokens
          npm publish --access public
          
          cd ../react
          npm publish --access public
        env:
          # Using the custom token name TAGADDOD_DESIGN
          NODE_AUTH_TOKEN: ${{ secrets.TAGADDOD_DESIGN }}
