name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Chromatic
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Build packages
        run: yarn build
      
      - name: Run Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build-storybook'
          workingDir: packages/storybook
          autoAcceptChanges: main
          exitZeroOnChanges: true  # Don't fail the build on visual changes
          exitOnceUploaded: true   # Exit as soon as the build is uploaded
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        continue-on-error: true  # Since Chromatic token might not be set up yet
      
      - name: Comment PR with Chromatic results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const chromaticComment = comments.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('Chromatic')
            );
            
            if (!chromaticComment) {
              console.log('No Chromatic comment found, visual tests might not be configured yet');
            }
        continue-on-error: true
